# Generated by Django 3.1.5 on 2021-01-22 22:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Drink',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=140)),
                ('start_sound', models.FileField(upload_to='audio')),
                ('ending_sound', models.FileField(upload_to='audio')),
            ],
        ),
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('is_alcohol', models.BooleanField(default=True)),
                ('cost', models.CharField(choices=[('$', 'Cheap'), ('$$', 'Normal'), ('$$$', 'Expensive'), ('$$$$', 'Too much')], max_length=4)),
            ],
        ),
        migrations.CreateModel(
            name='Resevoir',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('capacity', models.FloatField(default=16, help_text='In fluid ounces')),
                ('level', models.FloatField(default=80.0, help_text='In percentage')),
                ('motor_number', models.IntegerField(unique=True)),
                ('current_ingredient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.ingredient')),
            ],
        ),
        migrations.CreateModel(
            name='Instruction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pour_duration', models.IntegerField(default=500, help_text='How long to fire the motor for. In ms')),
                ('order', models.PositiveIntegerField()),
                ('ingredient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.ingredient')),
            ],
        ),
        migrations.CreateModel(
            name='DrinkCreationRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateField(auto_created=True)),
                ('source', models.CharField(help_text='Touchscreen, Text message', max_length=120)),
                ('drink', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.drink')),
            ],
        ),
        migrations.AddField(
            model_name='drink',
            name='ingredients',
            field=models.ManyToManyField(to='app.Ingredient'),
        ),
    ]
