# Generated by Django 3.1.5 on 2021-01-23 04:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='drink',
            name='ingredients',
        ),
        migrations.AddField(
            model_name='instruction',
            name='drink',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app.drink'),
            preserve_default=False,
        ),
        migrations.AddConstraint(
            model_name='instruction',
            constraint=models.UniqueConstraint(fields=('order', 'drink'), name='unique instruction order'),
        ),
    ]
