# Generated by Django 3.1.5 on 2021-01-23 06:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20210122_2310'),
    ]

    operations = [
        migrations.RenameField(
            model_name='resevoir',
            old_name='motor_number',
            new_name='gpio_pin',
        ),
        migrations.RemoveField(
            model_name='resevoir',
            name='current_ingredient',
        ),
        migrations.AddField(
            model_name='ingredient',
            name='resevoir',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ingredients', to='app.resevoir'),
        ),
        migrations.AlterField(
            model_name='instruction',
            name='ingredient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='instructions', to='app.ingredient'),
        ),
    ]
