# Generated by Django 3.1.5 on 2021-01-23 06:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20210123_0104'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drink',
            name='ending_sound',
            field=models.FileField(blank=True, null=True, upload_to='audio'),
        ),
        migrations.AlterField(
            model_name='drink',
            name='start_sound',
            field=models.FileField(blank=True, null=True, upload_to='audio'),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='resevoir',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ingredients', to='app.resevoir', unique=True),
        ),
    ]
