# Generated by Django 3.1.5 on 2021-01-23 19:16

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20210123_0115'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredient',
            name='resevoir',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ingredients', to='app.resevoir'),
        ),
        migrations.AlterField(
            model_name='resevoir',
            name='level',
            field=models.FloatField(default=80.0, help_text='In percentage', validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(1)]),
        ),
    ]
