# Generated by Django 3.1.5 on 2021-01-24 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20210123_1916'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drinkcreationrecord',
            name='created_at',
            field=models.DateField(auto_now_add=True),
        ),
    ]
