# Generated by Django 3.1.5 on 2021-01-24 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_auto_20210124_0240'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drinkcreationrecord',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
