# Generated by Django 3.1.5 on 2021-01-24 02:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_auto_20210124_0242'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instruction',
            name='drink',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='instructions', to='app.drink'),
        ),
    ]
